# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion_phase_1', models.TextField(default='', max_length=1000, verbose_name='Wiadomość powitalna')),
                ('describtion_phase_2', models.TextField(default='', max_length=1000, verbose_name='Instrukcja fazy GIL treningowej')),
                ('non_activity_time_GIL_try', models.IntegerField(default=10, verbose_name='Dozwolony czas braku aktywności fazy GIL treningowej')),
                ('describtion_phase_3', models.TextField(default='', max_length=1000, verbose_name='Instrukcja fazy GIL pomiarowej')),
                ('non_activity_time_GIL', models.IntegerField(default=10, verbose_name='Dozwolony czas braku aktywności fazy GIL pomiarowej')),
                ('duration_GIL_try', models.IntegerField(default=25, verbose_name='Czas trwania fazy GIL pomiarowej')),
                ('describtion_phase_4', models.TextField(default='', max_length=1000, verbose_name='Instrukcja fazy GIL wraz z wyborem kart - trening')),
                ('non_activity_time_cards_try', models.IntegerField(default=10, verbose_name='Dozwolony czas braku aktywności fazy GIL wraz z wyborem kart - trening')),
                ('duration_GIL_cards_try', models.IntegerField(default=25, verbose_name='Czas trwania fazy GIL wraz z wyborem kart - trening')),
                ('describtion_phase_5', models.TextField(default='', max_length=1000, verbose_name='Instrukcja fazy GIL wraz z wyborem kart - pomiar')),
                ('non_activity_time_cards', models.IntegerField(default=10, verbose_name='Dozwolony czas braku aktywności fazy GIL wraz z wyborem kart - pomiar')),
                ('number_of_sets', models.IntegerField(default=25, verbose_name='Liczba zadań fazy GIL wraz z wyborem kart - pomiar')),
            ],
            options={
                'verbose_name': 'Ustawienia eksperymentu',
                'verbose_name_plural': 'Ustawienia eksperymentu',
            },
        ),
        migrations.DeleteModel(
            name='GIL',
        ),
        migrations.DeleteModel(
            name='settings',
        ),
    ]
