# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0002_auto_20170215_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='experimentsettings',
            old_name='duration_GIL_cards_try',
            new_name='duration_cards_try',
        ),
        migrations.AddField(
            model_name='experimentsettings',
            name='duration_GIL',
            field=models.IntegerField(default=25, verbose_name='Czas trwania fazy GIL pomiarowej'),
        ),
        migrations.AlterField(
            model_name='experimentsettings',
            name='duration_GIL_try',
            field=models.IntegerField(default=25, verbose_name='Czas trwania fazy GIL treningowej'),
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karty.ExperimentSettings'),
        ),
    ]
