# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0003_auto_20170215_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(default='anonim', max_length=30)),
                ('age', models.IntegerField(default=77)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='currentsettings',
            options={'verbose_name': 'Obecne ustawienia eksperymentu', 'verbose_name_plural': 'Obecne ustawienia eksperymentu'},
        ),
    ]
