# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0005_experimentsettings_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentsettings',
            name='sex',
        ),
        migrations.AddField(
            model_name='experimentsettings',
            name='group_type',
            field=models.CharField(choices=[('1', 'Grupa kontrolna'), ('2', 'Grupa eksperymentalna pierwsza'), ('3', 'Grupa eksperymentalna druga')], default='1', max_length=1),
        ),
    ]
