# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0006_auto_20170217_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Historyjka', max_length=1000)),
                ('job', models.CharField(default='Zadanie', max_length=1000)),
                ('rule', models.CharField(default='Reguła', max_length=1000)),
            ],
            options={
                'verbose_name': 'Obecne ustawienia eksperymentu',
                'verbose_name_plural': 'Obecne ustawienia eksperymentu',
            },
        ),
        migrations.AddField(
            model_name='currentsettings',
            name='mode',
            field=models.CharField(choices=[('1', 'Tryb badawczy'), ('2', 'Tryb pilotażowy')], default='1', max_length=1),
        ),
    ]
