# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0007_auto_20170217_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsettings',
            name='mode',
            field=models.CharField(choices=[('1', 'Tryb badawczy'), ('2', 'Tryb pilotażowy')], default='1', max_length=1, verbose_name='Tryb'),
        ),
    ]
