# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0008_auto_20170217_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='job',
            new_name='implication_1',
        ),
        migrations.AddField(
            model_name='task',
            name='additional_description',
            field=models.CharField(default='Historyjka', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='implication_2',
            field=models.CharField(default='Zadanie', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='implication_3',
            field=models.CharField(default='Zadanie', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='implication_4',
            field=models.CharField(default='Zadanie', max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.CharField(default='Zadanie', max_length=1000),
        ),
    ]
