# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0009_auto_20170217_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Karta', max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Zadanie', 'verbose_name_plural': 'Zadania'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='implication_1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='implication_2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='implication_3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='implication_4',
        ),
        migrations.AddField(
            model_name='task',
            name='logic1',
            field=models.CharField(choices=[('P', 'P'), ('nP', 'NON-P'), ('Q', 'Q'), ('nQ', 'NON-Q')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='logic2',
            field=models.CharField(choices=[('P', 'P'), ('nP', 'NON-P'), ('Q', 'Q'), ('nQ', 'NON-Q')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='logic3',
            field=models.CharField(choices=[('P', 'P'), ('nP', 'NON-P'), ('Q', 'Q'), ('nQ', 'NON-Q')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='logic4',
            field=models.CharField(choices=[('P', 'P'), ('nP', 'NON-P'), ('Q', 'Q'), ('nQ', 'NON-Q')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='card1',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task',
            name='card2',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created2', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task',
            name='card3',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created3', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task',
            name='card4',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_requests_created4', to='karty.Card'),
        ),
    ]
