# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0010_auto_20170217_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='GIL_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karty.ExperimentSettings')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='karty.User')),
            ],
        ),
        migrations.AddField(
            model_name='gil_data',
            name='session',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='karty.Session'),
        ),
    ]
