# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0011_auto_20170217_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsettings',
            name='mode',
        ),
    ]
