# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0015_auto_20170225_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_data',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='karty.Task'),
        ),
    ]
