# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0016_task_data_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_presented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='karty.Session')),
                ('task', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='karty.Task')),
            ],
        ),
        migrations.AddField(
            model_name='gil_data',
            name='what',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task_data',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='karty.Task_presented'),
        ),
        migrations.AddField(
            model_name='gil_data',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='karty.Task_presented'),
        ),
    ]
