# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0017_auto_20170225_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_created', to='karty.Task')),
                ('second', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_created2', to='karty.Task')),
            ],
            options={
                'verbose_name_plural': 'Zadania treningowe',
                'verbose_name': 'Zadanie treningowe',
            },
        ),
    ]
