# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0018_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_presented',
            name='card1',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_presented_requests_created', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task_presented',
            name='card2',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_presented_requests_created2', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task_presented',
            name='card3',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_presented_requests_created3', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task_presented',
            name='card4',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='task_presented_requests_created4', to='karty.Card'),
        ),
        migrations.AddField(
            model_name='task_presented',
            name='overall_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task_presented',
            name='task_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='additional_description',
            field=models.CharField(default='Dodatkowy opis kart', max_length=1000),
        ),
    ]
