# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karty', '0019_auto_20170226_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='logic1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='logic2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='logic3',
        ),
        migrations.RemoveField(
            model_name='task',
            name='logic4',
        ),
        migrations.AddField(
            model_name='card',
            name='logic',
            field=models.CharField(choices=[('P', 'P'), ('nP', 'NON-P'), ('Q', 'Q'), ('nQ', 'NON-Q')], default='P', max_length=1),
        ),
    ]
